import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NavLinks } from '@/components/NavLinks';
import { ReduxProvider } from '@/store';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  authleft,
  authright,
}: {
  children: React.ReactNode;
  authleft: React.ReactNode;
  authright: React.ReactNode;
}) {
  console.info('>>> root layout renderer >>>');
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-2 border border-solid border-cyan-200 rounded`}
      >
        <ReduxProvider>
          <div>
            <div className="text-cyan-200">root layout page(all page show)</div>
            {authleft}
            {authright}
            <NavLinks />
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
