import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NavLinks } from '@/components/NavLinks';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.info('>>> root layout renderer >>>');
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-2 border border-solid border-cyan-200 rounded`}
      >
        <div className="text-cyan-200">layout page(all page show)</div>
        <NavLinks />
        {children}
      </body>
    </html>
  );
}
